name: CI/CD from Jenkinsfile

on:
  push:
    paths:
      - 'Jenkinsfile'
      - 'tools/jenkins_converter/**'
  workflow_dispatch:
    inputs:
      DEPLOY_ENV:
        description: "Environment to deploy"
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  convert:
    name: Convert Jenkinsfile
    runs-on: ubuntu-latest
    outputs:
      deploy_env: ${{ github.event.inputs.DEPLOY_ENV || 'dev' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install pyyaml

      - name: (Optional) Run converter to regenerate composite actions
        run: |
          # Placeholder: you can plug your parser here to rewrite .github/actions/*/action.yml
          echo "Conversion step - implement parser invocation."

  build:
    name: Build ✓
    runs-on: ubuntu-latest
    needs: convert
    steps:
      - name: Run build composite action
        uses: ./.github/actions/build
        with:
          DEPLOY_ENV: ${{ needs.convert.outputs.deploy_env }}

  test:
    name: Test ✓
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run test composite action
        uses: ./.github/actions/test

  deploy:
    name: Deploy ✓
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Run deploy composite action
        uses: ./.github/actions/deploy
        with:
          DEPLOY_ENV: ${{ needs.convert.outputs.deploy_env }}
